import React, { useEffect } from "react";
import { ArrowLeftIcon } from "@heroicons/react/outline";
import Head from "next/head";
import { useRouter } from "next/router";

import Feed from "../../components/Feed";
import { useDispatch } from "react-redux";
import { setActiveTab } from "../../store/AppSlice";

export default function CategoryPage({}) {
  const router = useRouter();
  const { name: categoryName, id: categoryId } = router.query;
  const d = useDispatch();

  return (
    <div>
      <Head>
        <title>{categoryName} | theBrif</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="xl:ml-[370px] border-l border-r border-gray-200  xl:min-w-[576px] sm:ml-[73px] flex-grow max-w-xl p-5">
        <div className="flex items-center space-x-2  py-2 px-3 sticky top-0 z-50 bg-white border-b border-gray-200">
          <div
            className="hoverEffect"
            onClick={() => {
              router.back();
            }}
          >
            <ArrowLeftIcon className="h-5 " />
          </div>
          <h2 className="text-lg sm:text-xl font-bold cursor-pointer">
            {categoryName}
          </h2>
        </div>
        <Feed category={categoryId as string} />
      </div>
    </div>
  );
}
