import Head from "next/head";

import Feed from "../components/Feed";

export default function Home({ categories }) {
  return (
    <div>
      <Head>
        <title>the Brif | News ARM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="xl:ml-[370px] border-l border-r border-gray-200  xl:min-w-[576px] sm:ml-[73px] flex-grow max-w-xl">
        <div className="flex py-2 px-3 sticky top-0 z-50 bg-white border-b border-gray-200">
          <h2 className="text-lg sm:text-xl font-bold cursor-pointer">Home</h2>
        </div>
        <Feed />
      </div>
    </div>
  );
}
