import Head from "next/head";

import Feed from "../components/Feed";

export default function Home({ categories }) {
  return (
    <div>
      <Head>
        <title>the Brif | News ARM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Feed />
    </div>
  );
}
