import { NextPage } from "next";
import Head from "next/head";

import Feed from "../components/Feed";
import Sidebar from "../components/Sidebar";
import Widgets from "../components/Widgets";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>the Brif | News ARM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen mx-auto">
        <Sidebar />

        <Feed />

        <Widgets newsResults={[]} randomUsersResults={null} />
      </main>
    </div>
  );
};

export default Home;
